#!/bin/sh

for f in ./src/*.*o; do
    rm -f $f
done

for f in ./src/*~; do
    rm -f $f
done

for f in ./R/*~; do
    rm -f $f
done

for f in ./man/*~; do
    rm -f $f
done

for f in *~; do
    rm -f $f
done

for f in .*~; do
    rm -f $f
done

for f in ./tests/*~; do
    rm -f $f
done

for f in ./tests/*.ps; do
    rm -f $f
done

for f in ./vignettes/*~; do
    rm -f $f
done

for f in ./vignettes/*.log; do
    rm -f $f
done

for f in ./vignettes/*.out; do
    rm -f $f
done

for f in ./vignettes/*.bbl; do
    rm -f $f
done

for f in ./vignettes/*.blg; do
    rm -f $f
done

for f in ./vignettes/*.brf; do
    rm -f $f
done

for f in ./vignettes/*.aux; do
    rm -f $f
done

for f in ./vignettes/*.tpt; do
    rm -f $f
done

for f in ./vignettes/Rplots*; do
    rm -f $f
done


find . -name "DEADJOE" -exec rm -f {} \;

exit 0
