#!/bin/sh

for f in ./src/*.*o; do
    rm -f $f
done

for f in ./src/*~; do
    rm -f $f
done

for f in ./R/*~; do
    rm -f $f
done

for f in ./man/*~; do
    rm -f $f
done

for f in *~; do
    rm -f $f
done

for f in .*~; do
    rm -f $f
done

for f in ./tests/*~; do
    rm -f $f
done

for f in ./tests/*.ps; do
    rm -f $f
done

for f in ./inst/doc/*~; do
    rm -f $f
done

for f in ./inst/doc/*.log; do
    rm -f $f
done

for f in ./inst/doc/*.out; do
    rm -f $f
done

for f in ./inst/doc/*.bbl; do
    rm -f $f
done

for f in ./inst/doc/*.blg; do
    rm -f $f
done

for f in ./inst/doc/*.brf; do
    rm -f $f
done

for f in ./inst/doc/*.aux; do
    rm -f $f
done


find . -name "DEADJOE" -exec rm -f {} \;

exit 0
